### ISSUE TITLE
Always Restarting on x64 processor.

### ISSUE THREAD

**Issue by abuttino** [blacksmithlabs/orbit-bhyve-remote#4]
Is this built for the new website? You can no longer get my.orbitbhyve.com (bought it yesterday) to add zones that means there are 0 zones showing on the API.

**Comment by killermonk** [comment]
@abuttino Per the original comment in my email, I never actually ran this on x64, so I can't say if it worked or not. I only ever ran it on my raspberry pi. I've since ported it over to firebase functions, so I run it from there.

It was still working as of last week on my firebase stuff, so I don't think the API has changed that I reversed for it. However, I do have my API token and set up from the old website that I'm using.

I'll have to check in to the new website. Can you give me any additional details on what you're seeing?

**Comment by killermonk** [comment]
I've reviewed the README instructions, and everything still works as defined for getting the device id. The zones aren't created on my.orbitbhyve.com, they are part of the system itself. My specific model has support for 6 zones that show up when I go to https://my.orbitbhyve.com/zones

What is it that you're trying to do that isn't being supported?

**Comment by abuttino** [comment]
It says invalid configuration but I know it's right. 

Is there a way to install this with npm instead? Docker always seems to screw me in one way or another.

**Comment by killermonk** [comment]
I have not set it up with npm in any way, because it reads a config file from a hard code path and docker restarts it if it crashes. Anything other than the API stuff itself didn't really feel fit for putting in npm. If you've already cloned the repo, you can just edit server.js to point at the location where you have your config file and then just run `npm i` and `npm start`.

I haven't fiddled with it in a while, but you could also sign up for an account on https://orbit-remote.web.app/ (or https://bhyve.blacksmithlabs.com/ point to the same place ), and set everything up to work through there.

I at least keep that one functional since I use it.

**Comment by killermonk** [comment]
@abuttino reading your comments on bhyve-mqtt, it looks like you're trying to use a hose timer? I have only ever tested this with a sprinkler controller. I have no idea if it will work with a hose timer as well, as I have never tested it.

**Comment by abuttino** [comment]
> I have not set it up with npm in any way, because it reads a config file from a hard code path and docker restarts it if it crashes. Anything other than the API stuff itself didn't really feel fit for putting in npm. If you've already cloned the repo, you can just edit server.js to point at the location where you have your config file and then just run `npm i` and `npm start`.
> 
> I haven't fiddled with it in a while, but you could also sign up for an account on https://orbit-remote.web.app/ (or https://bhyve.blacksmithlabs.com/ point to the same place ), and set everything up to work through there.
> 
> I at least keep that one functional since I use it.

What do I do with that information? Is that the information I am supposed to use for your node.js app?

You could always use 'forever' (or, np2, I believe) to make sure it starts even if it stops.

**Comment by killermonk** [comment]
My API was specifically reversed around starting and stopping my sprinklers in specific zones. I don't know if it will work for your timer.

However, the information was useful for this:

The first paragraph was some tidbits on how you can checkout the code and just configure it how you need to to run your own node.js app.

The second bit was the firebase app that I ported everything to and am currently using as my remote control. It automates the setup process for finding your device and getting the api token, etc. If you configure everything there, then you can set up the IFTTT integrations to enable voice commands, etc. It's all document on the website under the "IFTTT Setup Instructions" section.

My remote here was specifically built as a proxy to the API to allow for IFTTT (or your own custom) integrations with the Bhyve service (and specifically for sprinkler controllers). I'm not sure what your use case is, so I can't give you specific advice on your implementation without more information from you.

I will say this, though: this repository is only mildly maintained. I actively maintain the firebase app version, because that's what I use. That being said, I'm willing to help you make modifications to this code and/or merge your PRs, if you want to discuss your use case, but I'm not going to make any major modifications to this code.

**Comment by abuttino** [comment]
Right now I am on what could be my last step.

The MQTT side is working very well. Using EventGhost and a MQTT plugin and the Webserver plugin, I issue commands from webCoRE to turn the sprinkler on/off. 

That being said, there is no way I can get the values back from the server. Specifically, gallons.

Trying to write a simple notification to tell me cycle gallons and add to a variable for monthly gallons.

Presuming that you wrote the app, I would also be able to presume that you could tell me if I can get feedback on cycle_gallons.

**Comment by killermonk** [comment]
Unfortunately, my sprinkler timer appears to not have anything about that information, so I don't have any way of reverse engineering the messaging.

If you're interested in spending the time to reverse the messaging, I would be happy to help you add it to the code and test it.

If you go to the my.orbitbhyve.com and open the chrome inspector, then click the network tab, then click the "WS" filter, then log in, you will see a websocket open to wss://api.orbitbhyve.com/v1/events

You can monitor the messages across this websocket as you browse their website to get that information from them. If you can get a copy of the SND/RCV messages surrounding the information (or if it is included in the /devices request) then I'd be happy to help you go from there.

**Comment by abuttino** [comment]
I got it figured out with the MQTT client and SmartThings. A little touching up it's all good.

Just need to figure out one last thing, to get gallon reports without having to touch the center of the wheel on the app
